### ISSUE TITLE
Problem with exception handling

### ISSUE THREAD

**Issue by DavidvanDriessche** [om-mani-padme-hum/mysql-await#1]
Your package works great - however, I'm now trying to figure out how to do proper error handling when for example the database goes down. And I run into what I think is a systematic issue with the use of async ... await on the one hand and try ... catch on the other hand as implemented in this package.

The issue is is described here:
https://stackoverflow.com/questions/62392989/why-does-this-function-throw-an-exception-that-cannot-be-caught

I assumed the problem was with my code, but it appears to be with the code in the package **or** I don't understand how to use it properly. This issue was caused by `pool.query` giving an error (because I closed the database :)).

That causes a throw on line 505. This throw is not caught by `awaitQuery` itself, as the throw happens in an async function called by pool.query. It can as a result not be caught anywhere and kills node.js as a result. Which is not acceptable for me.

This would fix it:

```
this.pool.query(query, (err, result) => {
  if ( err ) {
    reject( err );
  } else {
    resolve( result );
  }
});
```

This causes the error to reject the promise, and as a result it can be caught using try catch in the code using `awaitQuery`:

```
try {
  const rows = await dbPool.awaitQuery(`SELECT * FROM users WHERE id = '${id}'`);
  [user = null] = rows;
  return user;
} catch (error) {
  console.log('database error');
  return null;
}

```
So, am I not understanding how I should use this code, or is this a legitimate issue that can be fixed in the package?

**Comment by om-mani-padme-hum** [comment]
Fixed in v2.1.2.  Thanks for the bug report!
